name: Go CI

on:
  push:
    branches: [ main ]   # 推送代码到 main 分支时触发
  pull_request:
    branches: [ main ]   # 针对 main 分支的 PR 触发

jobs:
  test:
    runs-on: ubuntu-latest  # 使用 Ubuntu 系统作为运行环境
    steps:
      - name: 检出代码
        uses: actions/checkout@v2  # 拉取仓库代码

      - name: 设置 Go 环境
        uses: actions/setup-go@v2  # 安装指定版本的 Go
        with:
          go-version: '1.20'       # 指定 Go 版本

      - name: 缓存依赖
        uses: actions/cache@v2     # 缓存 Go 模块加速后续构建
        with:
          path: ~/go/pkg/mod      # 缓存路径
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}  # 根据 go.sum 生成唯一 key

      - name: 运行测试
        run: go test -v ./...     # 执行所有测试（-v 显示详细输出）